apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: dashboard-secret-store
  namespace: prod
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "Dashboard-Secret"
        objectType: "secretsmanager"
    region: ap-south-1
  secretObjects:
    - secretName: dashboard-secret
      type: Opaque
      data:
        - objectName: "Dashboard-Secret"
          key: OPENAI_API_KEY
        - objectName: "Dashboard-Secret"
          key: NEXT_PUBLIC_API_BASE_URL
        - objectName: "Dashboard-Secret"
          key: NEXT_PUBLIC_RECAPTCHA_SITE_KEY
        - objectName: "Dashboard-Secret"
          key: NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY
